---
abstract: 'Create word cloud images'
author:
  - 'Brian Hann, C<< <brian.hann at gmail.com> >>'
  - 'Brian Hann <brian.hann@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-WordCloud
no_index:
  directory:
    - examples
    - inc
    - share
    - t
requires:
  Color::Scheme: 0
  File::Find::Rule: 0
  File::ShareDir: 0
  File::Spec: 0
  GD: 0
  GD::Text::Align: 0
  List::Util: 0
  Math::PlanePath::TheodorusSpiral: 0
  Params::Validate: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
